version: 2.1
jobs:
  build:
    docker:
      - image: shunichitakagi/build-tools:latest

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build docker image and tagged
          command: |
            IMAGE_ID=$(docker build . --quiet)
            docker tag $IMAGE_ID shunichitakagi/build-tools:0.0.1-build${CIRCLE_BUILD_NUM}
            docker tag $IMAGE_ID shunichitakagi/build-tools:latest

      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $USERNAME -p $PASSWORD

      - run:
          name: Push docker image with to Docker Hub
          command: |
            docker push shunichitakagi/build-tools:0.0.1-build${CIRCLE_BUILD_NUM}
            docker push shunichitakagi/build-tools:latest
