version: 2.1
jobs:
  build:
    docker:
      - image: shunichitakagi/build-tools:latest

    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          command: |
            echo 'export REVISION=build${CIRCLE_BUILD_NUM}-'$(date "+%Y%m%d%H%M%S") >> ${BASH_ENV}
          name: Setup environments

      - run:
          name: Build docker image and tagged
          command: |
            IMAGE_ID=$(docker build .)
            docker tag $IMAGE_ID shunichitakagi/build-tools:$REVISION
            docker tag $IMAGE_ID shunichitakagi/build-tools:latest

      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $USERNAME -p $PASSWORD

      - run:
          name: Push docker image with to Docker Hub
          command: |
            docker push shunichitakagi/build-tools:$REVISION
            docker push shunichitakagi/build-tools:latest
